### ISSUE TITLE
Exception during running example

### ISSUE THREAD

**Issue by Serwios** [androu-sys/drukarnia-api#4]
I've tried to run samile from your README

![image](https://github.com/androu-sys/drukarnia-api/assets/56473255/b76a947c-6685-44b3-95a6-4448e555a939)

And here is issue

![image](https://github.com/androu-sys/drukarnia-api/assets/56473255/89887ced-79d1-482f-b3b2-ca8d9a0b86c5)

Probably it's issue in versioning if so then please provide lists of needed dependecies with correct versions. 

Thanks for project!

**Comment by androu-sys** [comment]
# Hello :) Sorry for a late response

## Regarding your issue:

The problem is related to python's new versions. They reorganised `collections` module, which causes problems in many packages (particularly `attrdict` in this case)

Possible solutions:
    - upgrade "attrdict" package. By default it's "attrdict==2.0.1"
    - downgrade python version
    
## Regarding the package in general:

This package is not currently maintained, because I've not noticed a lot of activity around the platform in general. I may rewrite this package, if it's useful to someone)

**Comment by Serwios** [comment]
I've tried on python 3.8, 3.11.2 and 3.9.
Successfully script is working only on 3.9.
It would be nice to add specification for python version to use.

**Comment by androu-sys** [comment]
After some thought, I decided to renew the package to avoid future issues like this one. The new package will follow Python's best practices and include dependency/version configurations. The repository will be updated tomorrow morning.
